### ISSUE TITLE
Simplify guidelines documents

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-l10n/styleguides#89]
There are three documents in total in the guidelines folder. `outline.md` works great an `example_en-us.md` is a nice example of what you want to get as a result, despite not all headlines have the same wording as the outline, so it's sometime easy to get lost for a moment.

I have a slightly mixed feeling about the third document `styleguide_guidelines.md`. Up to `How to use these guidelines` and including the text is great, but the rest is what we (should) have in the outline directly.

May I have a look and merge the chapters after `How to use these guidelines` from `styleguide_guidelines.md` to `outline.md`?

#### Tasks
- [x] Merge sections from `styleguide_guidelines.md` (Formality and Tone and below) to `outline.md`. Keep the most complete information from both.
- [x] Unify the headlines between `outline.md` and `example_en-us.md`.
- [x] Update the text of `styleguide_guidelines.md` to refer to both other documents.

**Comment by flodolo** [comment]
@mozilla-l10n/pm-group thoughts?

**Comment by MikkCZ** [comment]
Speaking about guidelines to make a style guide, there is still [this document on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/L10n_Style_Guide), which is the same text what was in here before #53 too. Is it still there on purpose? If not, we should replace the content on MDN with some text to bring people here.

**Comment by flodolo** [comment]
As far as I know, we'll need to remove anything that it's not related to Web Standards from MDN.

**Comment by Delphine** [comment]
I see what you mean Michal. It seems like most of this is otherwise just a repetition. I think you could merge the chapters after `How to use these guidelines` from `styleguide_guidelines.md` to `outline.md` - making sure to keep the most complete version each time.

I'll give some other @mozilla-l10n/pm-group the chance to chime in here though, in case I'm missing anything. Also, maybe good to have @unclenachoduh add his thoughts, in case there was a specific reason for doing this - and that I may have forgotten since last summer?

**Comment by unclenachoduh** [comment]
These guidelines were originally meant to replace the MDN guidelines. I think that MDN page was supposed to come down at some point?

The original format of `outline.md` was a blank template and `styleguide_guidelines.md` contained the instructions for how to fill or adapt that template and descriptions of linguistic phenomena. When I first drafted the documents, I recognized that this format was potentially confusing. If it would be easier for translators if the information were consolidated into one document of instructions for writing a style guide, I think that should be done. The purpose of these documents is to make style guide creation *easier* for translators, not more difficult.

**Comment by Delphine** [comment]
Side note: @MikkCZ you mention that in `example_en-us.md` "not all headlines have the same wording as the outline, so it's sometime easy to get lost for a moment."
If it helps to align that wording, I think you can do that, too.

**Comment by gueroJeff** [comment]
sgtm :-)

And yes, the MDN page is supposed to come down. That's on my (lengthy)
to-do list.

**Comment by MikkCZ** [comment]
Thanks for all the feedback. I take it as a green light to give it a try. However I won't have enough time to start before the weekend, so if anyone is interested in the issue before I start, s/he is free to take it.
